### ISSUE TITLE
Repository logging for NETSTANDARD14

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-ipfs-engine#1]
The logging code for 1.4 has been `#if` out; because the logging factory interface has changed from .net standard 1.4 to 2.0.

**Comment by richardschneider** [comment]
Net standard 2 is not really there.  Blocked on https://github.com/net-commons/common-logging/issues/148

**Comment by Defee** [comment]
@richardschneider netstandard2.0 is now up. Should we unblock?

**Comment by richardschneider** [comment]
.Net Standard 1.4 is no longer supported #99
