### ISSUE TITLE
FormatException from AddFileAsync()

### ISSUE THREAD

**Issue by intfloatbool** [richardschneider/net-ipfs-engine#141]
When i try to upload video file at ipfs it throws FormatException...
FIle exists 100% and ready for upload, its easy to download by Client app, but from code it throws exception :-( 

`private async Task<string> UploadChunkFileASync(string fileName)
        {
            var filePath = StreamingWindow.VIDEO_PATH + fileName;

            if (!File.Exists(filePath))
            {
                Console.WriteLine("UNABLE TO LOAD FILE FROM: " + fileName);
                return string.Empty;
            }

            var fileNode = await _ipfsClient.FileSystem.AddFileAsync(filePath);

            return (string)fileNode.Id;
        }
`

**Comment by intfloatbool** [comment]
Invalid CID exception

**Comment by richardschneider** [comment]
Could you please add the stack trace!

`UploadChunkFileASync` will not compile and its name should be changed.

```
private async Task<string> UploadChunkFileAsync(string fileName)
{
   ...
}
```

For safety on different platforms, I would do
```
var filePath = Path.Combine(StreamingWindow.VIDEO_PATH, fileName);
```

**Comment by intfloatbool** [comment]
> Could you please add the stack trace!
> 
> `UploadChunkFileASync` will not compile and its name should be changed.
> 
> ```
> private async Task<string> UploadChunkFileAsync(string fileName)
> {
>    ...
> }
> ```
> 
> For safety on different platforms, I would do
> 
> ```
> var filePath = Path.Combine(StreamingWindow.VIDEO_PATH, fileName);
> ```

Stacktrace was not quite correctly i dont know why... mb because it cannot be showing succefull by metadata? I using nuget-package of your project.

About Task<T> i know about this thanks you :-)  , but problem not in this, just thrown "Invalid CID exception" inside of your dependicies. 
Path.Combine() nice , sometimes i forget about it, but file exists.

I use another .NET library for ipfs and its uploading great! Returned hash and uploading very fast , without exceptions. But i need to use DAG now , and its problem,  i will use CMD or HTTP for it )

**Comment by richardschneider** [comment]
Closing because you will not show stack trace
