### ISSUE TITLE
System.UnauthorizedAccessException: "The pass phrase is wrong."

### ISSUE THREAD

**Issue by simpo43** [richardschneider/net-ipfs-engine#150]
I use the code from the example
`var ipfs = new IpfsEngine("this is not a secure pass phrase".ToCharArray());
await ipfs.FileSystem.ReadAllTextAsync("QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/about");` 
and get an exception
`System.UnauthorizedAccessException: "The pass phrase is wrong."
PemException: problem creating ENCRYPTED private key: Org.BouncyCastle.Crypto.InvalidCipherTextException: pad block corrupted`
what's wrong?

**Comment by IlyaKrav** [comment]
Please, how u fix this?

**Comment by hsafarigithub** [comment]
use 
 System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
above that
