### ISSUE TITLE
TypeLoadException: VTable setup of type Ipfs.Engine.CoreApi.GenericApi failed

### ISSUE THREAD

**Issue by Im-Nick** [richardschneider/net-ipfs-engine#156]
Hi, i'm trying to implement ipfs on my unity project, but when i try to initialize the engine by 

`new IpfsEngine("".ToCharArray())`

it return 

`TypeLoadException: VTable setup of type Ipfs.Engine.CoreApi.GenericApi failed`

anyone know how to fix that?

**Comment by markhughes** [comment]
@x4NickU what was your solution ?

**Comment by Im-Nick** [comment]
i was using a bad dll's version , using ipfs.Engine & ipfs.http.client v0.42 whit ipfs.core v0.55.0 works

**Comment by Vytek** [comment]
@x4NickU I am very interesting using IPFS in Unity. Your project is open source?
