### ISSUE TITLE
Implementing PubSubApi

### ISSUE THREAD

**Issue by gavinuhma** [richardschneider/net-ipfs-engine#2]
## Context
We'd like to be able to use the `PubSubApi` of [net-ipfs-api](https://github.com/richardschneider/net-ipfs-api) without requiring the daemon. All of the `CoreApi` classes have been setup, and are ready to be implemented.

# Checklist:
- [x] write tests
- [x] dependency: https://github.com/libp2p/js-libp2p-keychain
- [x] dependency: https://github.com/libp2p/libp2p

**Comment by richardschneider** [comment]
@gavinuhma Thanks for your interest.  This is still very early days for this project. 
- The PubSubApi, and most other APIs, need a peer-2-peer communications framework; see [libp2p](https://github.com/libp2p/libp2p). 
- p2p needs crypto, so a [key chain](https://github.com/libp2p/js-libp2p-keychain) is needed

You could help by submitting a PR for PubSubApi tests.  Copy it from [net-ipfs-api](https://github.com/richardschneider/net-ipfs-api/blob/master/test/CoreApi/PubSubApiTest.cs) and make appropriate changes.

**Comment by gavinuhma** [comment]
Cool, thanks for the details! Updated the checklist

**Comment by richardschneider** [comment]
@gavinuhma 

- The Key API and Keychain have been implemented for some time. 
- p2p is being implemented in the PeerTalk project

Sorry for not updating you earlier.

**Comment by richardschneider** [comment]
PubSubApi is now available in [v0.8.0](https://github.com/richardschneider/net-ipfs-engine/releases/tag/v0.8.0). Please try it and report the issues.
