### ISSUE TITLE
Inline CID

### ISSUE THREAD

**Issue by richardschneider** [richardschneider/net-ipfs-engine#20]
Enhance BlockApi to handle an inline CID (hash algorithm is `identity`)

- [x] `GetAsync` should just work
- [x] `StatAsync` should just work
- [x] `RemoveAsync` should be a no-op
- [x] `PutAsync` should return inline CID when the option is enabled and possible

Enhance PinApi to handle an inline CID

- [x] ~~Never add/remove an inline CID to the PIN database~~

**Comment by richardschneider** [comment]
On second thought, inline CID should be added to the PIN database.  This way the end user can see the CID in the pin list.

**Comment by kevina** [comment]
@richardschneider want do you want me to comment on?
