### ISSUE TITLE
Builds new release

### ISSUE THREAD

**Issue by daef** [richardschneider/net-ipfs-engine#37]
The last release 0.0.1 (which I can install via nuget) is 99% of the commits behind.

**Comment by richardschneider** [comment]
The current state of the package is that it can only talk to other peers over a plain text connection.  By default other JS/GO peers require SECIO #41 to be supported by us. I don't see a need to release to NuGet until this is resolved.  

In the interim use [Ipfs.Api](https://github.com/richardschneider/net-ipfs-api) and restrict yourself to the [ICoreApi](https://richardschneider.github.io/net-ipfs-core/api/Ipfs.CoreApi.ICoreApi.html).  This will make it simple for your app to upgrade to `Ipfs.Engine`.

If you really want a NuGet release, I'll do it.  But please explain why you want it.

**Comment by daef** [comment]
I originally discovered this project searching for ipfs on NuGet - plus the project didn't seem abandoned - so why not ask I thought...
