### ISSUE TITLE
PubSubApi not implemented

### ISSUE THREAD

**Issue by keutmann** [richardschneider/net-ipfs-engine#78]
Hi

What are the chances of the file https://github.com/richardschneider/net-ipfs-engine/blob/master/src/CoreApi/PubSubApi.cs getting implemented?

I need the pubsub functionality in my solution to announce new files are when they are ready.
Currently, Im using the Go-lang implementation of IPFS with the C# HttpClient, but it would be nice to use the C# engine implementation of IPFS, because it makes deployment and control easier. My App is a decentralized solution and therefore needs to be as simple as possible to distribute.
Do you have any other recommendation for a similar solution to PubSub, that is based on C#?

Thank you
Carsten

**Comment by richardschneider** [comment]
Thanks for your interest.

I'm now  looking at pubsub both flooding and gossip.  Watch this space.

Are you interested on helping with the implementation?

**Comment by richardschneider** [comment]
PubSubApi is now available in [v0.8.0](https://github.com/richardschneider/net-ipfs-engine/releases/tag/v0.8.0). Please try it and report the issues.

**Comment by keutmann** [comment]
Great thanks!
